// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdP2PGEzLy4Y1Pc50pF6cwkDdufMTdHE',
    appId: '1:1080429668130:android:74db100f23ff30b28d677b',
    messagingSenderId: '1080429668130',
    projectId: 'lifesparktask1',
    storageBucket: 'lifesparktask1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXsJgOyXR2QKIAFGMV61qJsfaswrf7Zq0',
    appId: '1:1080429668130:ios:5822639c873f9aef8d677b',
    messagingSenderId: '1080429668130',
    projectId: 'lifesparktask1',
    storageBucket: 'lifesparktask1.appspot.com',
    iosBundleId: 'com.example.lifespakTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXsJgOyXR2QKIAFGMV61qJsfaswrf7Zq0',
    appId: '1:1080429668130:ios:5822639c873f9aef8d677b',
    messagingSenderId: '1080429668130',
    projectId: 'lifesparktask1',
    storageBucket: 'lifesparktask1.appspot.com',
    iosBundleId: 'com.example.lifespakTask',
  );
}
